export const RequestData = [
    {
        id:"1",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"2",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"3",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"4",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"5",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"6",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"7",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"8",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"9",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"10",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"11",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"12",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"13",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"14",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"15",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"16",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"17",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"18",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"19",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"20",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"21",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"22",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"23",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"24",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"25",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"26",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },
    {
        id:"27",
        startdate:"1/1/2001",
        enddate:"2/2/2001",
        device:"iPhone XR",
        makemodel:"Apple Mobile",
        request:"First name last name",
        justification:"Lorem ipsum dolor sit amet",
        status:"Approved",
        remark:"Software upgrade overdue"
    },


]